//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPlatform.FMService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FMService.FMService1Soap")]
    public interface FMService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnFileInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnFileInfo(string businessNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnFileInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnFileInfoAsync(string businessNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnMainFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnMainFile(string businessNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnMainFile", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReturnMainFileAsync(string businessNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransferFile2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet TransferFile2(string addressNo, System.Data.DataSet dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransferFile2", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> TransferFile2Async(string addressNo, System.Data.DataSet dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransferMainFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TransferMainFile(string addressNo, string businessNo, string newName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TransferMainFile", ReplyAction="*")]
        System.Threading.Tasks.Task<string> TransferMainFileAsync(string addressNo, string businessNo, string newName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FMService1SoapChannel : MvcPlatform.FMService.FMService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FMService1SoapClient : System.ServiceModel.ClientBase<MvcPlatform.FMService.FMService1Soap>, MvcPlatform.FMService.FMService1Soap {
        
        public FMService1SoapClient() {
        }
        
        public FMService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FMService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FMService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FMService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ReturnFileInfo(string businessNo) {
            return base.Channel.ReturnFileInfo(businessNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnFileInfoAsync(string businessNo) {
            return base.Channel.ReturnFileInfoAsync(businessNo);
        }
        
        public System.Data.DataSet ReturnMainFile(string businessNo) {
            return base.Channel.ReturnMainFile(businessNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReturnMainFileAsync(string businessNo) {
            return base.Channel.ReturnMainFileAsync(businessNo);
        }
        
        public System.Data.DataSet TransferFile2(string addressNo, System.Data.DataSet dt) {
            return base.Channel.TransferFile2(addressNo, dt);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> TransferFile2Async(string addressNo, System.Data.DataSet dt) {
            return base.Channel.TransferFile2Async(addressNo, dt);
        }
        
        public string TransferMainFile(string addressNo, string businessNo, string newName) {
            return base.Channel.TransferMainFile(addressNo, businessNo, newName);
        }
        
        public System.Threading.Tasks.Task<string> TransferMainFileAsync(string addressNo, string businessNo, string newName) {
            return base.Channel.TransferMainFileAsync(addressNo, businessNo, newName);
        }
    }
}
