//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcPlatform.WeChatServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeChatServer.BGServiceSoap")]
    public interface BGServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TemplateSend", ReplyAction="*")]
        void TemplateSend();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TemplateSend", ReplyAction="*")]
        System.Threading.Tasks.Task TemplateSendAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginExceptionSend", ReplyAction="*")]
        void LoginExceptionSend();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginExceptionSend", ReplyAction="*")]
        System.Threading.Tasks.Task LoginExceptionSendAsync();
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetAccessTokenResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccessToken", ReplyAction="*")]
        MvcPlatform.WeChatServer.GetAccessTokenResponse GetAccessToken(MvcPlatform.WeChatServer.GetAccessTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccessToken", ReplyAction="*")]
        System.Threading.Tasks.Task<MvcPlatform.WeChatServer.GetAccessTokenResponse> GetAccessTokenAsync(MvcPlatform.WeChatServer.GetAccessTokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccessTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccessToken", Namespace="http://tempuri.org/", Order=0)]
        public MvcPlatform.WeChatServer.GetAccessTokenRequestBody Body;
        
        public GetAccessTokenRequest() {
        }
        
        public GetAccessTokenRequest(MvcPlatform.WeChatServer.GetAccessTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAccessTokenRequestBody {
        
        public GetAccessTokenRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccessTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccessTokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public MvcPlatform.WeChatServer.GetAccessTokenResponseBody Body;
        
        public GetAccessTokenResponse() {
        }
        
        public GetAccessTokenResponse(MvcPlatform.WeChatServer.GetAccessTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAccessTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAccessTokenResult;
        
        public GetAccessTokenResponseBody() {
        }
        
        public GetAccessTokenResponseBody(string GetAccessTokenResult) {
            this.GetAccessTokenResult = GetAccessTokenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BGServiceSoapChannel : MvcPlatform.WeChatServer.BGServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BGServiceSoapClient : System.ServiceModel.ClientBase<MvcPlatform.WeChatServer.BGServiceSoap>, MvcPlatform.WeChatServer.BGServiceSoap {
        
        public BGServiceSoapClient() {
        }
        
        public BGServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BGServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BGServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BGServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void TemplateSend() {
            base.Channel.TemplateSend();
        }
        
        public System.Threading.Tasks.Task TemplateSendAsync() {
            return base.Channel.TemplateSendAsync();
        }
        
        public void LoginExceptionSend() {
            base.Channel.LoginExceptionSend();
        }
        
        public System.Threading.Tasks.Task LoginExceptionSendAsync() {
            return base.Channel.LoginExceptionSendAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MvcPlatform.WeChatServer.GetAccessTokenResponse MvcPlatform.WeChatServer.BGServiceSoap.GetAccessToken(MvcPlatform.WeChatServer.GetAccessTokenRequest request) {
            return base.Channel.GetAccessToken(request);
        }
        
        public string GetAccessToken() {
            MvcPlatform.WeChatServer.GetAccessTokenRequest inValue = new MvcPlatform.WeChatServer.GetAccessTokenRequest();
            inValue.Body = new MvcPlatform.WeChatServer.GetAccessTokenRequestBody();
            MvcPlatform.WeChatServer.GetAccessTokenResponse retVal = ((MvcPlatform.WeChatServer.BGServiceSoap)(this)).GetAccessToken(inValue);
            return retVal.Body.GetAccessTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MvcPlatform.WeChatServer.GetAccessTokenResponse> MvcPlatform.WeChatServer.BGServiceSoap.GetAccessTokenAsync(MvcPlatform.WeChatServer.GetAccessTokenRequest request) {
            return base.Channel.GetAccessTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<MvcPlatform.WeChatServer.GetAccessTokenResponse> GetAccessTokenAsync() {
            MvcPlatform.WeChatServer.GetAccessTokenRequest inValue = new MvcPlatform.WeChatServer.GetAccessTokenRequest();
            inValue.Body = new MvcPlatform.WeChatServer.GetAccessTokenRequestBody();
            return ((MvcPlatform.WeChatServer.BGServiceSoap)(this)).GetAccessTokenAsync(inValue);
        }
    }
}
